# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2abf1ef1c50dcd90b7e98741f52541d08dccbe9e9b123bd5d8d537c757700ed6b6597c1784b37ecbbba2f42f8aa0132abee8bb8e9d6c916de415d54768149b03

test:
  secret_key_base: 67cc1156428d687c717616cec9e9450ed984cd3e4aa3a49c7082901ee49a395ec00235d994282ebf3f5fe74830d3d48b98fee56e9cd1d5b6fce8e6a27d250aba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
